---
# Role tasks

- block:
    - block:
        - name: Setup tftpd server args in systemd unit
          lineinfile:
            path: /usr/lib/systemd/system/tftp.service
            regexp: '^ExecStart='
            line: >-
              ExecStart=/usr/sbin/in.tftpd
              -s {{ tftpd_root_directory }}
              {{ tftpd_server_args }}
          register: tftpd_setup_sytemd_result

        - name: Enable and start tftpd service
          systemd:
            name: tftp
            enabled: yes
            daemon_reload: yes

        - name: Enable and start tftp socket
          systemd:
            name: tftp.socket
            enabled: yes
            state: started
      when: tftpd_state == "present"
  tags:
    - role::tftpd
