---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    dockerfile: ../resources/Dockerfile.systemd.j2
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/side_effect.yml
  inventory:
    group_vars:
      molecule_hosts:
        tftpd_state: absent

      molecule_hosts_fedora:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
